services:
  - type: web
    name: mi-dotnet-app
    env: docker  # o 'static' si no docker, pero docker es más reproducible
    repo: https://github.com/IDGS-903-22001411/congreso-backend
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
