// <auto-generated />
using System;
using CongresoAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CongresoAPI.Migrations
{
    [DbContext(typeof(BdCongresoContext))]
    [Migration("20251109030914_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("CongresoAPI.Models.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ocupacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Twitter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Participantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Pérez",
                            Avatar = "https://i.pravatar.cc/150?img=1",
                            Email = "carlos.perez@example.com",
                            FechaRegistro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos",
                            Ocupacion = "Desarrollador",
                            Twitter = "@carlosp"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Gómez",
                            Avatar = "https://i.pravatar.cc/150?img=2",
                            Email = "ana.gomez@example.com",
                            FechaRegistro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana",
                            Ocupacion = "Diseñadora",
                            Twitter = "@anagomez"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Martínez",
                            Avatar = "https://i.pravatar.cc/150?img=3",
                            Email = "luis.martinez@example.com",
                            FechaRegistro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Luis",
                            Ocupacion = "Estudiante",
                            Twitter = "@luism"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
